/**
 * generated by Xtext
 */
package com.br.terra.dcl.validation;

import com.br.terra.dcl.validation.AbstractDCLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DCLValidator extends AbstractDCLValidator {
}
